apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if .Values.replicaSet.enabled }}
    kind: ReplicaSet
    name: "{{ .Release.Name }}-rs"
    {{- end }}
    {{- if .Values.deployment.enabled }}
    kind: Deployment
    name: "{{ .Release.Name }}-deployment"
    {{- end }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  metrics:
{{- with .Values.hpa.cpuUtilization.targetPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- with .Values.hpa.memoryUtilization.targetPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}